import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { styled } from "@/styled-system/jsx";

const defaultFont = localFont({
  src: [
    {
      path: "../public/fonts/IBMPlexSansKR-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/IBMPlexSansKR-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/IBMPlexSansKR-Regular.ttf",
      weight: "400",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={defaultFont.className}>
      <Body>{children}</Body>
    </html>
  );
}

const Body = styled("body", {
  base: {
    backgroundColor: "primary.02",
  },
});
